### ISSUE TITLE
Incorrect content. `and` and `or` can be used within .query() method.

### ISSUE THREAD

**Issue by mattcarr17** [learn-co-curriculum/dsc-using-sql-with-pandas#1]
## Link to Canvas

https://github.com/learn-co-curriculum/dsc-using-sql-with-pandas

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```
Note that if you want to use and and or statements with the .query() method, you'll need to use "&" and "|" instead.
```

### Concern

These instructions are unclear/incorrect. Both `and` and `or` statements work within `.query()` so long as they are lowercase. `AND` and `OR` throw an error. 

## (Optional) Proposed Solution

```
Note that if you want to use `AND` and `OR` statements with the .query() method, you'll need to make them lowercase (`and` and `or`) or use "&" and "|" instead.
```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] IllumiDesk

**Comment by bpurdy-ds** [comment]
Correct and updated. https://github.com/learn-co-curriculum/dsc-using-sql-with-pandas/issues/1#issue-1222999460
